name: Docker CICD Pipeline
on:
 push:
  branches:
     - master

jobs:
 build-test-deploy:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v3
   - name: Login to Docker hub
     env:
      username: ${{secrets.DOCKER_USERNAME}}
      password: ${{secrets.DOCKER_PASSWORD}}
     run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
     
   - name: Build  the Docker image
     run: docker build -t cicd-dockerpipelineex
   - name: Push to dockerhub
     run: docker push swagi/cicd-dockerpipelineex:latest
    
     
     
  

